version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres:15.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - pgdata:/data/postgres
    ports:
      - 5432:5432
    networks:
      - pgNet
    deploy:
      restart_policy:
        condition: any

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - ${PGADMIN_PORT:-5050}:80
    networks:
      - pgNet
    deploy:
      restart_policy:
        condition: any

volumes:
  pgdata:
  pgadmin:

networks:
  pgNet:
    driver: overlay
    
