version: "3.9"

services:
  postgres:
    image: postgres:15.2
    hostname: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - pgdata:/data/postgres
    configs:
      - source: create-user.sql
        target: /docker-entrypoint-initdb.d/create-user.sql
        mode: 440
    ports:
      - 5432:5432
    networks:
      - pgNet
    deploy:
      restart_policy:
        condition: any

  pgadmin:
    image: dpage/pgadmin4:latest
    hostname: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - ${PGADMIN_PORT:-5050}:80
    networks:
      - pgNet
    deploy:
      restart_policy:
        condition: any

configs:
  create-user.sql:
    name: create-user-${timestamp}.sql
    file: ./create-user.sql

volumes:
  pgdata:
  pgadmin:

networks:
  pgNet:
    driver: overlay
